version: '3'

services:
  project1:
    container_name: practice-2
    build: .
    ports:
      - 8000:8000
      - 8100:8100

  prometheus:
    user: root
    container_name: prometheus
    image: prom/prometheus:latest
    depends_on:
      - project1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /tmp/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    ports:
      - 3001:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
      #     -  grafana-storage:grafana/grafana
      - grafanadata:/var/lib/grafana
    env_file:
      - ./config.monitoring

  redis:
    image: "redis:alpine"
    ports:
      - 6380:6379

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3307:3306


  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - 2182:2181

  kafka:
    container_name: kakfa
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29092

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

## Volume mount in local to mac to grafan container run by docker.
#volumes:
#  grafana-storage:
#    driver: local

volumes:
  grafanadata:
