version: '3'

services:
  project1:
    container_name: practice-2
    build: .
    ports:
      - 8000:8000

  example-prometheus:
    image: prom/prometheus:latest
    container_name: example-prometheus
    depends_on:
      - project1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  example-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: example-grafana
    depends_on:
      - example-prometheus
    ports:
      - 4000:4000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
      - ..grafana-storage:/var/lib/grafana grafana/grafana
    env_file:
      - ./config.monitoring