// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.application.genproto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcexample.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
