// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.application.genproto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcexample.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
