// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.application.genproto;

public final class Message {
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_grpcexample_HelloRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_grpcexample_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_grpcexample_HelloReply_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_grpcexample_HelloReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\rmessage.proto\022\013grpcexample\")\n\014HelloReq" +
                    "uest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"\035\n\nHello" +
                    "Reply\022\017\n\007message\030\001 \001(\t2\222\001\n\007Greeter\022@\n\010Sa" +
                    "yHello\022\031.grpcexample.HelloRequest\032\027.grpc" +
                    "example.HelloReply\"\000\022E\n\rSayHelloAgain\022\031." +
                    "grpcexample.HelloRequest\032\027.grpcexample.H" +
                    "elloReply\"\000B\034\n\030com.application.genprotoP" +
                    "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_grpcexample_HelloRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_grpcexample_HelloRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grpcexample_HelloRequest_descriptor,
            new String[]{"Name", "Age",});
    internal_static_grpcexample_HelloReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_grpcexample_HelloReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grpcexample_HelloReply_descriptor,
            new String[]{"Message",});
  }
  private Message() {}

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
